cargo-features = ["codegen-backend"]

[package]
name = "dots"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
tokio = { version = "1.43.0", features = ["fs", "macros", "sync", "rt"] }
